version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "80:80"
    networks:
      - back_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./secret_hitler/build/web:/var/www/html/secret_hitler/web



networks:
  back_network:
    driver: bridge
